language: python
python:
  - "2.7"
install:
  - pip install -U setuptools tox coveralls tox-travis
script:
  - tox
after_success:
  - coveralls
notifications:
  email:
    on_success: always
    on_failure: always
